//! Pachinko Allocation Model (Li & McCallum, "Pachinko Allocation: DAG-Structured
//! Mixture Models of Topic Correlations", ICML 2006) — the four-level / two-tier
//! version. Where LDA has a single layer of topics, PAM inserts an extra layer of
//! **super-topics** between the document and the topics, so correlations *between*
//! topics are modeled explicitly.
//!
//! The DAG has four levels: root → S super-topics → K sub-topics → words. Crucially
//! the sub-topics are **shared** across super-topics (this is a DAG, not a tree):
//! every super-topic can mix any of the K sub-topics, and two super-topics may
//! prefer overlapping or disjoint sub-topic sets. Each document `d` carries:
//!   - a multinomial over super-topics, `Dirichlet(alpha)` symmetric over S; and
//!   - for *each* super-topic `s`, a multinomial over sub-topics, drawn from a
//!     super-topic-specific Dirichlet with parameter vector `α_s = (α_{s1}..α_{sK})`.
//! Each sub-topic `k` is a multinomial over the vocabulary, `Dirichlet(beta)`.
//! A word token is generated by sampling a path: first a super-topic `s`, then a
//! sub-topic `k`, then a word `w ~ φ_k`.
//!
//! The **per-super-topic α_s vectors are the model's only globally shared link
//! between a super-topic and the sub-topics it prefers** — and are what give the
//! super-topics a stable identity across documents (without them the S
//! super-topics are exchangeable and never specialize). They are *initialized
//! asymmetrically* — super-topic `s` mildly prefers the slice of sub-topics around
//! `s·K/S`, which breaks the label symmetry — held fixed through a burn-in, then
//! **adapted to the data** (Li & McCallum §3, "we estimate α") by moment-matching
//! each α_s toward the super-topic's pooled sub-topic usage at a fixed total
//! concentration. Documents are also *committed* to a single random super-topic at
//! initialization, giving the super-topic layer something to specialize on.
//!
//! Inference is a **collapsed Gibbs sampler** over the per-token pair `g=(s,k)`,
//! integrating out the document multinomials and the topic-word multinomials
//! (Li & McCallum §3). Removing token (d, w)'s current pair, we draw
//!
//!   p(s,k) ∝ (n_ds + alpha)
//!            · (n_dsk + α_{sk}) / (n_ds + Σ_j α_{sj})
//!            · (n_kw  + beta)   / (n_k  + V·beta).
//!
//! The first factor is the document→super-topic term, the second the
//! super→sub-topic term (now with the estimated asymmetric prior), and the third
//! the sub-topic→word emission. (The document→super normalizer `n_d + S·alpha` is
//! constant across all (s,k) for a fixed token, so it cancels and is omitted here.)
//! We enumerate all S·K pairs and sample proportionally.
//!
//! Approximations: (a) the original paper also re-estimates the document→super
//! prior; we hold that symmetric and fixed at `alpha`, adapting only the
//! per-super-topic α_s sub-topic vectors. (b) Rather than the unconstrained Minka
//! Dirichlet-MLE (which, on the extremely sparse per-document sub-topic usage of
//! the four-level model, collapses α toward 0 and erases the super-topics' global
//! identity), we adapt α_s by fixed-concentration moment matching, which keeps the
//! prior informative and stable. The sampler is self-contained and deterministic
//! for a fixed `rng`.

use rand::Rng;
use crate::estimator::{Estimator, ModelFamily, DirichletModel};

/// A fitted Pachinko Allocation model (four-level, two-tier).
pub struct PamModel {
    pub num_types: usize, // V, vocabulary size
    pub num_super: usize, // S, number of super-topics
    pub num_sub: usize,   // K, number of sub-topics
    pub alpha: f64,       // symmetric Dirichlet prior on the doc→super multinomial
    pub beta: f64,        // symmetric Dirichlet prior on the sub-topic→word multinomials
    pub alpha_sk: Vec<Vec<f64>>,  // S × K  estimated super→sub Dirichlet parameters
    pub nkw: Vec<Vec<u32>>,       // K × V  sub-topic ↦ word counts
    pub nk: Vec<u32>,             // K      sub-topic totals
    pub nds: Vec<Vec<u32>>,       // D × S  doc ↦ super-topic counts
    pub ndsk: Vec<Vec<Vec<u32>>>, // D × S × K  doc ↦ (super, sub) counts
    pub zs: Vec<Vec<usize>>, // per-document token super-topic assignments
    pub zk: Vec<Vec<usize>>, // per-document token sub-topic assignments
    /// Thinned θ draws (num_draws, D, K): sub-topic proportions marginalized
    /// over super-topics at each snapshot. Empty when draw_cap=0.
    pub theta_draws: Vec<Vec<Vec<f32>>>,
}

impl PamModel {
    pub fn num_super(&self) -> usize {
        self.num_super
    }

    pub fn num_sub(&self) -> usize {
        self.num_sub
    }

    /// Sub-topic word distributions φ_{k,w} = (n_{kw}+β)/(n_k+Vβ), shape K×V.
    /// Each row is a proper distribution over the vocabulary.
    pub fn topic_word(&self) -> Vec<Vec<f64>> {
        let v = self.num_types;
        self.nkw
            .iter()
            .zip(&self.nk)
            .map(|(row, &nk)| {
                let denom = nk as f64 + v as f64 * self.beta;
                row.iter().map(|&c| (c as f64 + self.beta) / denom).collect()
            })
            .collect()
    }

    /// Document ↦ sub-topic mixtures, shape D×K, marginalizing over super-topics.
    /// We take the smoothed marginal sub-topic count
    /// `θ_{d,k} ∝ (Σ_s n_{dsk}) + alpha` and normalize each row to sum to 1.
    pub fn doc_topic(&self) -> Vec<Vec<f64>> {
        let k = self.num_sub;
        self.ndsk
            .iter()
            .map(|doc| {
                let mut row = vec![0.0f64; k];
                for sub in 0..k {
                    let mut total = 0u32;
                    for s in 0..self.num_super {
                        total += doc[s][sub];
                    }
                    row[sub] = total as f64 + self.alpha;
                }
                let s: f64 = row.iter().sum();
                if s > 0.0 {
                    for x in row.iter_mut() {
                        *x /= s;
                    }
                }
                row
            })
            .collect()
    }

    /// Super-topic ↦ sub-topic association, shape S×K. Entry (s,k) is the smoothed
    /// posterior mean of the super→sub multinomial pooled over documents, using the
    /// estimated prior: `(Σ_d n_{dsk} + α_{sk}) / (Σ_d n_{ds} + Σ_j α_{sj})`.
    /// Reading a row tells you which sub-topics a super-topic groups together.
    pub fn super_sub(&self) -> Vec<Vec<f64>> {
        let s_count = self.num_super;
        let k = self.num_sub;
        let mut out = vec![vec![0.0f64; k]; s_count];
        for s in 0..s_count {
            let mut sk_totals = vec![0u32; k];
            let mut s_total = 0u32;
            for doc in &self.ndsk {
                for sub in 0..k {
                    sk_totals[sub] += doc[s][sub];
                    s_total += doc[s][sub];
                }
            }
            let alpha_sum: f64 = self.alpha_sk[s].iter().sum();
            let denom = s_total as f64 + alpha_sum;
            for sub in 0..k {
                out[s][sub] = (sk_totals[sub] as f64 + self.alpha_sk[s][sub]) / denom;
            }
        }
        out
    }
}

impl Estimator for PamModel {
    fn num_topics(&self) -> usize { self.num_sub }
    fn topic_word(&self) -> Vec<Vec<f64>> { PamModel::topic_word(self) }
    fn doc_topic(&self) -> Vec<Vec<f64>> { PamModel::doc_topic(self) }
    fn fit_history(&self) -> Vec<(usize, f64)> { Vec::new() }
    fn converged(&self) -> Option<bool> { None }
    fn model_family(&self) -> ModelFamily { ModelFamily::Dirichlet }
}

impl DirichletModel for PamModel {
    fn alpha(&self) -> Vec<f64> { vec![self.alpha; self.num_sub] }
    fn theta_draws(&self) -> Vec<Vec<Vec<f64>>> {
        self.theta_draws.iter().map(|d| {
            d.iter().map(|r| r.iter().map(|&x| x as f64).collect()).collect()
        }).collect()
    }
    fn doc_lengths(&self) -> Vec<usize> {
        self.zk.iter().map(|d| d.len()).collect()
    }
}

fn sample_index<R: Rng>(probs: &[f64], rng: &mut R) -> usize {
    let total: f64 = probs.iter().sum();
    let mut r = rng.gen::<f64>() * total;
    for (i, &p) in probs.iter().enumerate() {
        r -= p;
        if r <= 0.0 {
            return i;
        }
    }
    probs.len() - 1
}

impl PamModel {
    /// Draw a `(super, sub)` pair for token (d, i)=w from the current state (the
    /// token's counts must already be removed) and add the token back under the
    /// chosen pair.
    fn assign_token<R: Rng>(&mut self, d: usize, i: usize, w: usize, probs: &mut [f64], rng: &mut R) {
        let v = self.num_types;
        let s_count = self.num_super;
        let k = self.num_sub;
        let n_d: u32 = self.nds[d].iter().sum();
        // The doc→super normalizer (n_d + S·alpha) cancels across pairs, but we
        // include it for clarity/numeric scaling.
        let super_norm = n_d as f64 + s_count as f64 * self.alpha;

        // `probs` is a reusable scratch buffer (one allocation per sweep, not per
        // token); the s_count·k entries are all overwritten below.
        for s in 0..s_count {
            let nds = self.nds[d][s] as f64;
            let super_term = (nds + self.alpha) / super_norm;
            let alpha_sum: f64 = self.alpha_sk[s].iter().sum();
            let sub_norm = nds + alpha_sum;
            for sub in 0..k {
                let sub_super = (self.ndsk[d][s][sub] as f64 + self.alpha_sk[s][sub]) / sub_norm;
                let emit = (self.nkw[sub][w] as f64 + self.beta)
                    / (self.nk[sub] as f64 + v as f64 * self.beta);
                probs[s * k + sub] = super_term * sub_super * emit;
            }
        }

        let g = sample_index(probs, rng);
        let s = g / k;
        let sub = g % k;

        self.nds[d][s] += 1;
        self.ndsk[d][s][sub] += 1;
        self.nkw[sub][w] += 1;
        self.nk[sub] += 1;
        self.zs[d][i] = s;
        self.zk[d][i] = sub;
    }

    /// One full Gibbs sweep over every token.
    fn sweep<R: Rng>(&mut self, docs: &[Vec<u32>], rng: &mut R) {
        let mut probs = vec![0.0f64; self.num_super * self.num_sub];
        for (d, doc) in docs.iter().enumerate() {
            for (i, &w) in doc.iter().enumerate() {
                let w = w as usize;
                let s_old = self.zs[d][i];
                let k_old = self.zk[d][i];
                self.nds[d][s_old] -= 1;
                self.ndsk[d][s_old][k_old] -= 1;
                self.nkw[k_old][w] -= 1;
                self.nk[k_old] -= 1;
                self.assign_token(d, i, w, &mut probs, rng);
            }
        }
    }

    /// Re-estimate each super-topic's asymmetric sub-topic prior `α_s` by moment
    /// matching its *direction* to the pooled super→sub usage, at a fixed total
    /// concentration `conc = K·alpha·CONC_SCALE`. For super-topic `s` we form the
    /// smoothed pooled distribution
    ///   p_{sk} = (Σ_d n_{dsk} + α_{sk}) / (Σ_d n_{ds} + Σ_j α_{sj})
    /// and set α_{sk} ← conc · p_{sk}. Holding the concentration fixed (rather than
    /// running the unconstrained Minka MLE, which on this very sparse per-document
    /// usage collapses α toward 0 and erases the super-topics' global identity)
    /// keeps the prior informative and lets each super-topic *keep* a stable
    /// preference for the sub-topics it has come to own, sharpening it toward the
    /// data. This is the form of α-adaptation that gives PAM its correlated-topic
    /// structure; the unconstrained MLE is the "approximation we avoid" noted up top.
    fn estimate_alpha_sk(&mut self) {
        const CONC_SCALE: f64 = 4.0;
        let k = self.num_sub;
        let conc = k as f64 * self.alpha * CONC_SCALE;
        let ss = self.super_sub(); // pooled, smoothed super→sub distributions
        for (s, p) in ss.iter().enumerate() {
            let psum: f64 = p.iter().sum();
            if psum <= 0.0 {
                continue;
            }
            for sub in 0..k {
                self.alpha_sk[s][sub] = (conc * p[sub] / psum).max(1e-3);
            }
        }
    }
}

impl PamModel {
    /// Collapsed Gibbs log-likelihood for PAM marginalizing over super-topics.
    /// Uses the sub-topic document counts summed over super-topics and the
    /// sub-topic word counts, matching the marginal LDA-style formula.
    pub fn log_likelihood(&self, docs: &[Vec<u32>]) -> f64 {
        use crate::optimize::digamma;
        let k = self.num_sub;
        let v = self.num_types;
        let k_alpha = k as f64 * self.alpha;
        let v_beta = v as f64 * self.beta;
        let mut ll = 0.0f64;

        // Document-topic (marginal sub-topic) contribution.
        for (d, doc) in docs.iter().enumerate() {
            let n_d = doc.len() as f64;
            for sub in 0..k {
                let n_dk: u32 = (0..self.num_super).map(|s| self.ndsk[d][s][sub]).sum();
                let n_dk = n_dk as f64;
                if n_dk > 0.0 {
                    ll += digamma(self.alpha + n_dk) - digamma(self.alpha);
                }
            }
            ll -= digamma(k_alpha + n_d) - digamma(k_alpha);
        }

        // Sub-topic word contribution.
        for sub in 0..k {
            for w in 0..v {
                let n_kw = self.nkw[sub][w] as f64;
                if n_kw > 0.0 {
                    ll += digamma(self.beta + n_kw) - digamma(self.beta);
                }
            }
            ll -= digamma(v_beta + self.nk[sub] as f64) - digamma(v_beta);
        }

        ll
    }
}

/// Fit a Pachinko Allocation model by collapsed Gibbs sampling. Each document is
/// committed to a single random super-topic at initialization (with random
/// sub-topics per token); the model is then refined by `iters` Gibbs sweeps. The
/// per-super-topic sub-topic priors `α_s` start asymmetric (to break the
/// super-topic label symmetry), are held fixed through a burn-in, then adapted to
/// the data over the final quarter of the sweeps. Deterministic for a fixed `rng`.
#[allow(clippy::too_many_arguments)]
pub fn fit_pam<R: Rng>(
    docs: &[Vec<u32>],
    num_types: usize,
    num_super: usize,
    num_sub: usize,
    alpha: f64,
    beta: f64,
    iters: usize,
    rng: &mut R,
) -> PamModel {
    // Plain fit is the draw-collecting fit with collection disabled, so the
    // sampler lives in exactly one place (see `fit_pam_with_draws`).
    let (model, _, _) = fit_pam_with_draws(
        docs, num_types, num_super, num_sub, alpha, beta, iters,
        crate::keyatm::ThetaDrawOpts::new(false, 0, 0),
        0.0, 0,
        rng,
    );
    model
}

/// Fit a PAM with thinned θ snapshots (sub-topic proportions, marginalized over
/// super-topics) collected every `thin` sweeps, ring-buffered to `cap` draws.
/// `cap=0` disables collection entirely.
///
/// Returns `(model, ll_history, converged)`.
#[allow(clippy::too_many_arguments)]
pub fn fit_pam_with_draws<R: Rng>(
    docs: &[Vec<u32>],
    num_types: usize,
    num_super: usize,
    num_sub: usize,
    alpha: f64,
    beta: f64,
    iters: usize,
    opts: crate::keyatm::ThetaDrawOpts,
    convergence_tol: f64,
    check_every: usize,
    rng: &mut R,
) -> (PamModel, Vec<(usize, f64)>, bool) {
    let d = docs.len();
    let k = num_sub;

    // Break the super-topic label symmetry with a structured prior: super-topic
    // `s` mildly prefers the contiguous slice of sub-topics around `s·K/S`. This
    // only biases which super-topic owns which sub-topic slots; the sub-topic to
    // vocabulary mapping is still learned, and the asymmetric-alpha re-estimate
    // can move the preference. Without it the super-topics stay exchangeable and
    // never specialize.
    let alpha_sk: Vec<Vec<f64>> = (0..num_super)
        .map(|s| {
            (0..num_sub)
                .map(|kk| {
                    let owner = (kk * num_super) / num_sub;
                    if owner == s { alpha * 5.0 } else { alpha }
                })
                .collect()
        })
        .collect();
    let mut model = PamModel {
        num_types,
        num_super,
        num_sub,
        alpha,
        beta,
        alpha_sk,
        nkw: vec![vec![0u32; num_types]; num_sub],
        nk: vec![0u32; num_sub],
        nds: vec![vec![0u32; num_super]; d],
        ndsk: vec![vec![vec![0u32; num_sub]; num_super]; d],
        zs: docs.iter().map(|doc| vec![0usize; doc.len()]).collect(),
        zk: docs.iter().map(|doc| vec![0usize; doc.len()]).collect(),
        theta_draws: Vec::new(),
    };

    for (di, doc) in docs.iter().enumerate() {
        let s = (rng.gen::<f64>() * num_super as f64) as usize % num_super;
        for (i, &w) in doc.iter().enumerate() {
            let w = w as usize;
            let sub = (rng.gen::<f64>() * num_sub as f64) as usize % num_sub;
            model.nds[di][s] += 1;
            model.ndsk[di][s][sub] += 1;
            model.nkw[sub][w] += 1;
            model.nk[sub] += 1;
            model.zs[di][i] = s;
            model.zk[di][i] = sub;
        }
    }

    let adapt_after = iters - iters / 4;
    let mut ll_history: Vec<(usize, f64)> = Vec::new();
    let mut converged = false;

    for it in 0..iters {
        model.sweep(docs, rng);
        if it >= adapt_after {
            model.estimate_alpha_sk();
        }
        let iter = it + 1;
        if opts.thin > 0 && iter % opts.thin == 0 {
            let snap: Vec<Vec<f32>> = model.ndsk.iter().map(|doc| {
                let mut row = vec![0.0f64; k];
                for sub in 0..k {
                    let total: u32 = (0..model.num_super).map(|s| doc[s][sub]).sum();
                    row[sub] = total as f64 + model.alpha;
                }
                let s: f64 = row.iter().sum();
                row.iter().map(|&x| (if s > 0.0 { x / s } else { 1.0 / k as f64 }) as f32).collect()
            }).collect();
            if model.theta_draws.len() < opts.cap {
                model.theta_draws.push(snap);
            } else {
                model.theta_draws.remove(0);
                model.theta_draws.push(snap);
            }
        }
        // Trace recording and optional convergence check (never alters RNG).
        if check_every > 0 && iter % check_every == 0 {
            let ll = model.log_likelihood(docs);
            ll_history.push((iter, ll));
            if convergence_tol > 0.0 && ll_history.len() >= 2 {
                let prev = ll_history[ll_history.len() - 2].1;
                let rel = (ll - prev).abs() / (prev.abs() + 1e-12);
                if rel < convergence_tol {
                    converged = true;
                    break;
                }
            }
        }
    }

    (model, ll_history, converged)
}

#[cfg(test)]
mod tests {
    use super::*;
    use rand_chacha::rand_core::SeedableRng;
    use rand_chacha::ChaCha8Rng;

    /// Build a corpus with K=4 disjoint-vocabulary sub-topic blocks grouped into
    /// S=2 super-topics: super-topic 0 owns blocks {0,1}, super-topic 1 owns
    /// blocks {2,3}. Each document draws from BOTH blocks of ONE super-topic, so
    /// the two sub-topics inside a super-topic co-occur (but never cross between
    /// super-topics). The block mixing ratio varies per document so the two
    /// always-co-occurring sub-topics stay individually identifiable. Flat LDA
    /// would see four topics with no notion of the grouping; PAM should recover
    /// both the blocks and the grouping.
    fn planted_corpus() -> (Vec<Vec<u32>>, Vec<Vec<u32>>, [[usize; 2]; 2], usize) {
        let blocks: Vec<Vec<u32>> = (0..4).map(|b| (b * 6..b * 6 + 6).collect()).collect();
        let v = 24;
        let groups = [[0usize, 1], [2, 3]]; // super-topic ↦ its two planted blocks
        let mut docs = Vec::new();
        for d in 0..400 {
            let g = d % 2; // which super-topic this document belongs to
            let pair = groups[g];
            let n0 = 8 + (d / 2) % 17; // 8..=24 tokens from the first block
            let n1 = 32 - n0; // the rest from the second block
            let mut doc = Vec::new();
            for t in 0..n0 {
                let blk = &blocks[pair[0]];
                doc.push(blk[(t + d) % blk.len()]);
            }
            for t in 0..n1 {
                let blk = &blocks[pair[1]];
                doc.push(blk[(t + d) % blk.len()]);
            }
            docs.push(doc);
        }
        (docs, blocks, groups, v)
    }

    #[test]
    fn recovers_planted_blocks_and_grouping() {
        let (docs, blocks, groups, v) = planted_corpus();
        let mut rng = ChaCha8Rng::seed_from_u64(42);
        let model = fit_pam(&docs, v, 2, 4, 0.1, 0.01, 200, &mut rng);

        // (1) Each sub-topic's top words concentrate on a single planted block.
        // Map each sub-topic to the block its top-6 words fill.
        let tw = model.topic_word();
        let mut sub_to_block = vec![usize::MAX; 4];
        for (k, row) in tw.iter().enumerate() {
            let mut idx: Vec<usize> = (0..v).collect();
            idx.sort_by(|&a, &b| row[b].partial_cmp(&row[a]).unwrap());
            let top: std::collections::HashSet<usize> = idx[..6].iter().copied().collect();
            for (bi, blk) in blocks.iter().enumerate() {
                if blk.iter().all(|&w| top.contains(&(w as usize))) {
                    sub_to_block[k] = bi;
                }
            }
            assert_ne!(
                sub_to_block[k], usize::MAX,
                "sub-topic {} top words do not fill a single planted block",
                k
            );
        }
        // All four blocks should be covered, one per sub-topic (a bijection).
        let covered: std::collections::HashSet<usize> = sub_to_block.iter().copied().collect();
        assert_eq!(covered.len(), 4, "sub-topics did not recover all 4 blocks: {:?}", sub_to_block);

        // (2) The super_sub() matrix groups the co-occurring sub-topics. For each
        // super-topic take its top-2 sub-topics, translate to the blocks they
        // represent, and check they equal one planted group (match up to
        // permutation of super-topics).
        let ss = model.super_sub();
        let top2_blocks = |s: usize| -> std::collections::HashSet<usize> {
            let row = &ss[s];
            let mut idx: Vec<usize> = (0..4).collect();
            idx.sort_by(|&a, &b| row[b].partial_cmp(&row[a]).unwrap());
            idx[..2].iter().map(|&k| sub_to_block[k]).collect()
        };
        let recovered: Vec<std::collections::HashSet<usize>> = (0..2).map(top2_blocks).collect();
        let planted: Vec<std::collections::HashSet<usize>> = groups
            .iter()
            .map(|g| g.iter().copied().collect())
            .collect();

        // Match super-topics to planted groups up to permutation.
        let matches = |perm: [usize; 2]| -> bool {
            recovered[0] == planted[perm[0]] && recovered[1] == planted[perm[1]]
        };
        assert!(
            matches([0, 1]) || matches([1, 0]),
            "super_sub grouping {:?} does not match planted groups {:?}",
            recovered,
            planted
        );
    }

    #[test]
    fn deterministic_for_fixed_seed() {
        let docs: Vec<Vec<u32>> = (0..50)
            .map(|d| (0..10).map(|i| ((i + d) % 12) as u32).collect())
            .collect();
        let mut r1 = ChaCha8Rng::seed_from_u64(7);
        let mut r2 = ChaCha8Rng::seed_from_u64(7);
        let m1 = fit_pam(&docs, 12, 2, 4, 0.1, 0.01, 30, &mut r1);
        let m2 = fit_pam(&docs, 12, 2, 4, 0.1, 0.01, 30, &mut r2);
        assert_eq!(m1.topic_word(), m2.topic_word());
    }

    #[test]
    fn pam_conforms() {
        let docs: Vec<Vec<u32>> = (0..40)
            .map(|d| (0..8).map(|i| ((i + d * 3) % 12) as u32).collect())
            .collect();
        let mut rng = ChaCha8Rng::seed_from_u64(11);
        let m = fit_pam(&docs, 12, 2, 3, 0.1, 0.01, 20, &mut rng);
        let base = crate::conformance::check_conformance(&m);
        assert!(base.is_empty(), "check_conformance: {:?}", base);
        let dir = crate::conformance::check_dirichlet(&m);
        assert!(dir.is_empty(), "check_dirichlet: {:?}", dir);
    }
}
