"""Emit the paper's "Computational details" block from the live toolchain.

JSS requires a computational-details statement pinning the versions behind every
reported number. Rather than hand-maintain it, this script detects what is
installed and prints the block; paste its output into the Availability section of
`topica.tex`, and rerun it whenever the toolchain moves.

    VIRTUAL_ENV="$PWD/.venv-dev" .venv-dev/bin/python paper/computational_details.py

Anything not installed is reported as such (never silently dropped), so the block
honestly records the environment that produced the artifacts in this repository.
"""

import platform
import re
import shutil
import subprocess


def _run(cmd):
    """Return stripped stdout+stderr of a command, or None if it is unavailable."""
    exe = cmd[0]
    if shutil.which(exe) is None:
        return None
    try:
        p = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        return ((p.stdout or "") + (p.stderr or "")).strip()
    except Exception:
        return None


def pyver(mod):
    try:
        return __import__(mod).__version__
    except Exception:
        return None


def main():
    # --- the package and its Python stack ---------------------------------
    py = platform.python_version()
    topica = pyver("topica")
    stack = {name: pyver(name) for name in
             ("numpy", "scipy", "scikit-learn".replace("-", "_") and "sklearn",
              "matplotlib", "plotly")}

    # --- the Rust core build toolchain ------------------------------------
    rustc = _run(["rustc", "--version"])
    rustc = rustc.split()[1] if rustc else None

    # --- reference implementations used in validation/performance ---------
    java = _run(["java", "-version"])
    java = re.search(r'"([^"]+)"', java).group(1) if java else None

    mallet = None
    brew = _run(["brew", "list", "--versions", "mallet"])
    if brew:
        build = brew.split()[-1]
        # Homebrew dates the MALLET build (e.g. 202108); the upstream release is 2.0.8.
        mallet = f"2.0.8 (Homebrew build {build})" if build.isdigit() else build

    rver = _run(["Rscript", "--version"])
    rver = re.search(r"version (\d+\.\d+\.\d+)", rver).group(1) if rver else None
    rpkgs = {}
    if shutil.which("Rscript"):
        out = _run(["Rscript", "-e",
                    'for (p in c("stm","keyATM","tm")) '
                    'cat(p, tryCatch(as.character(packageVersion(p)), '
                    'error=function(e) "NA"), "\\n")'])
        for line in (out or "").splitlines():
            parts = line.split()
            if len(parts) == 2:
                rpkgs[parts[0]] = parts[1]

    arch = platform.machine()
    if platform.system() == "Darwin":
        silicon = " (Apple Silicon)" if arch == "arm64" else ""
        osname = f"macOS {platform.mac_ver()[0]}{silicon}"
    else:
        osname = f"{platform.system()} {platform.release()}"

    # --- emit -------------------------------------------------------------
    def fmt(v):
        return v if v else "not installed"

    print("% --- generated by paper/computational_details.py; do not hand-edit ---")
    print("The results in this article were produced with \\pkg{topica}~"
          f"{fmt(topica)} on \\proglang{{Python}}~{py}, with")
    print(f"\\pkg{{NumPy}}~{fmt(stack['numpy'])}, \\pkg{{SciPy}}~{fmt(stack['scipy'])}, "
          f"\\pkg{{scikit-learn}}~{fmt(stack['sklearn'])}, "
          f"\\pkg{{Matplotlib}}~{fmt(stack['matplotlib'])}, and "
          f"\\pkg{{Plotly}}~{fmt(stack['plotly'])}.")
    print(f"The \\proglang{{Rust}} core was compiled with \\code{{rustc}}~{fmt(rustc)}.")
    print("The cross-implementation checks of Section~\\ref{sec:validation} and the "
          "timings of")
    print("Section~\\ref{sec:performance} ran the reference packages "
          f"\\proglang{{Java}}~{fmt(java)} \\pkg{{MALLET}}~{fmt(mallet)} and "
          f"\\proglang{{R}}~{fmt(rver)} with")
    print(f"\\pkg{{stm}}~{fmt(rpkgs.get('stm'))} and "
          f"\\pkg{{keyATM}}~{fmt(rpkgs.get('keyATM'))}.")
    print(f"All computations were performed on {osname}, {arch}.")


if __name__ == "__main__":
    main()
